name: "HostlocAutoGetPoints"

on:
  push:
    branches:
      - main
      # - master
  # schedule:
  #   - cron: "0 16 * * *"

jobs:
  build:
    # if: ${{ github.repository_owner == 'weilining' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout codes"
        uses: actions/checkout@v2
      - name: "Set python"
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: "Install dependencies"
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt -t .
      - name: "Get points"
        env:
          HOSTLOC_USERNAME: ${{ secrets.HOSTLOC_USERNAME }}
          HOSTLOC_PASSWORD: ${{ secrets.HOSTLOC_PASSWORD }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python index.py
